<a href="https://colab.research.google.com/github/yash5891/Deep-Learning/blob/main/01_Deep_LearningRegression_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Introduction to Linear Regression

In [ ]:
import torch
import numpy as np

In [ ]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

In [ ]:
inputs

array([[ 73.,  67.,  43.],
       [ 91.,  88.,  64.],
       [ 87., 134.,  58.],
       [102.,  43.,  37.],
       [ 69.,  96.,  70.]], dtype=float32)

In [ ]:
# Targets (apples)
targets = np.array([[56,81,119,22,103]],dtype = 'float32')
targets.reshape((-1,1))

array([[ 56.],
       [ 81.],
       [119.],
       [ 22.],
       [103.]], dtype=float32)

In [ ]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [ ]:
inputs[0]

tensor([73., 67., 43.])

In [ ]:
targets

tensor([[ 56.,  81., 119.,  22., 103.]])

## Linear regression model from scratch

In [ ]:
w = torch.randn(1,3, requires_grad= True)
b = torch.randn(1, requires_grad= True)


In [ ]:
w

tensor([[-0.9488,  0.9185,  0.0071]], requires_grad=True)

In [ ]:
b

tensor([1.1182], requires_grad=True)

In [ ]:
def model(x):
    return x @ w.t() + b

In [ ]:
preds = model(inputs)

In [ ]:
preds

tensor([[ -6.2978],
        [ -3.9382],
        [ 42.0665],
        [-55.8999],
        [ 24.3260]], grad_fn=<AddBackward0>)

## Loss function

In [ ]:
def mse(t1, t2):
  diff = t1 - t2
  return torch.sum((diff**2))/ diff.numel()

In [ ]:
loss = mse(preds, targets)
print(loss)

tensor(8090.6421, grad_fn=<DivBackward0>)


## Compute gradients

In [ ]:
loss.backward()

In [ ]:
w.grad

tensor([[-13335.2090, -11125.4395,  -7669.9473]])

In [ ]:
lr = 1e-5
with torch.no_grad():
    w -= w.grad * lr
    b -= b.grad * lr



In [ ]:
loss = mse(preds, targets)
loss

tensor(8090.6421, grad_fn=<DivBackward0>)

In [ ]:
w.grad.zero_()
b.grad.zero_()

tensor([0.])

In [ ]:
lr = 1e-5
with torch.no_grad():
    w -= w.grad * lr
    b -= b.grad * lr
    w.grad.zero_()
    b.grad.zero_()

In [ ]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(5123.4214, grad_fn=<DivBackward0>)


In [ ]:
lr = 1e-5
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * lr
        b -= b.grad * lr
        w.grad.zero_()
        b.grad.zero_()

In [ ]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(1385.2415, grad_fn=<DivBackward0>)


In [ ]:
preds

tensor([[60.1844],
        [78.7044],
        [96.0154],
        [57.4454],
        [76.6975]], grad_fn=<AddBackward0>)

In [ ]:
targets

tensor([[ 56.,  81., 119.,  22., 103.]])

## Linear regression using PyTorch built-ins

In [ ]:
from torch import nn

In [ ]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70],
                   [74, 66, 43],
                   [91, 87, 65],
                   [88, 134, 59],
                   [101, 44, 37],
                   [68, 96, 71],
                   [73, 66, 44],
                   [92, 87, 64],
                   [87, 135, 57],
                   [103, 43, 36],
                   [68, 97, 70]],
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 81, 119, 22, 103, 57, 80, 118, 21, 104, 57, 82, 118, 20,102]],
                   dtype='float32').reshape(-1,1)

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [ ]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

In [ ]:
targets

tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.],
        [ 57.],
        [ 80.],
        [118.],
        [ 21.],
        [104.],
        [ 57.],
        [ 82.],
        [118.],
        [ 20.],
        [102.]])

## Dataset and DataLoader

Create a `TensorDataset`, which allows access to rows from `inputs` and `targets` as tuples, and provides standard APIs for working with many different types of datasets in PyTorch.

In [ ]:
from torch.utils.data import TensorDataset

In [ ]:
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.],
         [ 81.],
         [119.]]))

The `TensorDataset` allows us to access a small section of the training data using the array indexing notation (`[0:3]` in the above code). It returns a tuple with two elements. The first element contains the input variables for the selected rows, and the second contains the targets.

We'll also create a `DataLoader`, which can split the data into batches of a predefined size while training. It also provides other utilities like shuffling and random sampling of the data.

In [ ]:
from torch.utils.data import DataLoader

In [ ]:
bs = 5
train_loader = DataLoader(train_ds, batch_size = bs, shuffle = True)


In [ ]:
for xb, yb in train_loader:
    print(xb)
    print(yb)
    break

tensor([[ 73.,  67.,  43.],
        [101.,  44.,  37.],
        [ 69.,  96.,  70.],
        [ 92.,  87.,  64.],
        [ 73.,  66.,  44.]])
tensor([[ 56.],
        [ 21.],
        [103.],
        [ 82.],
        [ 57.]])


In [ ]:
# model = nn.Linear(3, 1)
# print(model.weight)
# print(model.bias)

##  Building the PyTorch Model Class
We can create the logistic regression model with the following code:

In [ ]:
class Linear_Regression(torch.nn.Module):
     def __init__(self, input_dim, output_dim):
         super(Linear_Regression, self).__init__()
         self.linear = torch.nn.Linear(input_dim, output_dim)
     def forward(self, x):
         outputs = self.linear(x)
         return outputs

In [ ]:

model = Linear_Regression(3,1)

In [ ]:
list(model.parameters())

In [ ]:
preds = model(inputs)
preds

## Loss Function

In [ ]:
import torch.nn.functional as F

In [ ]:
loss_fn = F.mse_loss

In [ ]:
loss = loss_fn(model(inputs), targets)
print(loss)

## Optimizer

Instead of manually manipulating the model's weights & biases using gradients, we can use the optimizer `optim.SGD`. SGD is short for "stochastic gradient descent". The term stochastic indicates that samples are selected in random batches instead of as a single group.

In [ ]:
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

## Train the model
We are now ready to train the model. We'll follow the same process to implement gradient descent:

  1. Generate predictions

  2. Calculate the loss

  3. Compute gradients w.r.t the weights and biases

  4. Adjust the weights by subtracting a small quantity proportional to the gradient

  5. Reset the gradients to zero

The only change is that we'll work batches of data instead of processing the entire training data in every iteration. Let's define a utility function `fit` that trains the model for a given number of epochs.

In [ ]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):

    # Repeat for given number of epochs
    for epoch in range(num_epochs):

        # Train with batches of data
        for xb,yb in train_dl:

            # 1. Generate predictions
            pred = model(xb)

            # 2. Calculate loss
            loss = loss_fn(pred, yb)

            # 3. Compute gradients
            loss.backward()

            # 4. Update parameters using gradients
            opt.step()

            # 5. Reset the gradients to zero
            opt.zero_grad()

        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [ ]:
fit(100, model, loss_fn, opt, train_loader)

In [ ]:
preds = model(inputs)
preds

In [ ]:
targets

In [ ]:
model(torch.tensor([[75, 63, 44.]]))