<a href="https://colab.research.google.com/github/yash5891/Deep-Learning/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch


In [ ]:
a = torch.rand(3,4)
a


tensor([[0.1671, 0.7984, 0.2427, 0.3673],
        [0.0220, 0.2145, 0.4369, 0.4160],
        [0.1762, 0.9298, 0.6155, 0.9953]])

In [ ]:
a = torch.empty(3,4)
a

tensor([[ 1.0530e+29,  4.5706e-41, -1.1796e-11,  3.2402e-41],
        [-1.1780e-11,  3.2402e-41, -1.1795e-11,  3.2402e-41],
        [ 0.0000e+00,  0.0000e+00, -1.1693e-11,  3.2402e-41]])

In [ ]:
a = torch.zeros(3, 4)
a

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
a = torch.zeros(3, 4, dtype=torch.long)
a#.short=inttype=16 .long=inttype64


tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [ ]:
a = torch.tensor([[10, 20, 4],
                  [0, 0, 4]])
a

tensor([[10, 20,  4],
        [ 0,  0,  4]])

In [ ]:
import numpy as np

a = np.ones(7)
b = torch.from_numpy(a)
a, b

(array([1., 1., 1., 1., 1., 1., 1.]),
 tensor([1., 1., 1., 1., 1., 1., 1.], dtype=torch.float64))

In [ ]:
import numpy as np

a = np.ones(7)
b = torch.from_numpy(a)
a, b

(array([1., 1., 1., 1., 1., 1., 1.]),
 tensor([1., 1., 1., 1., 1., 1., 1.], dtype=torch.float64))

In [ ]:
import numpy as np

a = np.ones(7)
x = np.ones(7)
b = torch.from_numpy(x)
a, b
b.numpy()

array([1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b *= 2
a,b

(array([1., 1., 1., 1., 1., 1., 1.]),
 tensor([2., 2., 2., 2., 2., 2., 2.], dtype=torch.float64))

In [ ]:
a = torch.rand(4,3)
b = torch.rand(4,3)
a+b

tensor([[1.4425, 0.8348, 1.1554],
        [1.3374, 0.9112, 0.6040],
        [0.3607, 0.7049, 0.5037],
        [1.0107, 0.9152, 0.5634]])

In [ ]:
torch.add(a,b)


tensor([[1.4425, 0.8348, 1.1554],
        [1.3374, 0.9112, 0.6040],
        [0.3607, 0.7049, 0.5037],
        [1.0107, 0.9152, 0.5634]])

In [ ]:
result = torch.empty(4, 3)
torch.add(a, b, out=result) # stored in tensor `result`.
result

tensor([[1.4425, 0.8348, 1.1554],
        [1.3374, 0.9112, 0.6040],
        [0.3607, 0.7049, 0.5037],
        [1.0107, 0.9152, 0.5634]])

In [ ]:
a = torch.rand(3,4)
b = torch.rand(4,5)
c = torch.mm(a,b)
c

tensor([[1.6939, 1.5859, 1.0151, 0.7490, 1.7239],
        [1.7190, 1.1276, 1.0479, 1.3452, 1.1782],
        [1.7163, 1.4201, 0.9159, 1.1210, 1.6488]])

In [ ]:
a@b

tensor([[1.6939, 1.5859, 1.0151, 0.7490, 1.7239],
        [1.7190, 1.1276, 1.0479, 1.3452, 1.1782],
        [1.7163, 1.4201, 0.9159, 1.1210, 1.6488]])

In [ ]:
a.sum(), a.min(), a.max()

(tensor(7.4850), tensor(0.2796), tensor(0.9774))

In [ ]:
a[0, 0].item() # float data type


0.5485432147979736

In [ ]:
a = torch.rand(1,3,1,4)
b=a.shape, a.squeeze().shape
b

(torch.Size([1, 3, 1, 4]), torch.Size([3, 4]))

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device_cpu = torch.device('cpu')  # CPU
device_gpu = torch.device('cuda') # GPU
device_cpu, device_gpu

(device(type='cpu'), device(type='cuda'))

In [ ]:
# prompt: Import torch and print the version number.

import torch
print(torch.__version__)


2.3.0+cu121


In [ ]:
# prompt:  Create a 1D tensor of numbers from 0 to 9

torch.arange(10)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# prompt:  Question: Create a 2D tensor of shape 5x3 to contain random decimal numbers between 5 and 10.

import torch

# Create a 2D tensor of shape 5x3 with random decimal numbers between 5 and 10
tensor = torch.randint(5,9,(5, 3))


# Print the tensor
print(tensor)


tensor([[8, 7, 8],
        [7, 5, 8],
        [5, 6, 5],
        [7, 8, 5],
        [6, 6, 8]])


In [ ]:
# prompt:  Create a 3×3 tensor of all True’s

a = torch.ones(3,3, dtype=torch.bool)
a

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [ ]:
a=torch.arange(1,100,2)
a

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
        37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71,
        73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [ ]:
# prompt: eplace all odd numbers in above arr with -1

a = torch.arange(1,100)
a[a % 2 != 0] = -1
a


tensor([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10, -1, 12, -1, 14, -1, 16, -1, 18,
        -1, 20, -1, 22, -1, 24, -1, 26, -1, 28, -1, 30, -1, 32, -1, 34, -1, 36,
        -1, 38, -1, 40, -1, 42, -1, 44, -1, 46, -1, 48, -1, 50, -1, 52, -1, 54,
        -1, 56, -1, 58, -1, 60, -1, 62, -1, 64, -1, 66, -1, 68, -1, 70, -1, 72,
        -1, 74, -1, 76, -1, 78, -1, 80, -1, 82, -1, 84, -1, 86, -1, 88, -1, 90,
        -1, 92, -1, 94, -1, 96, -1, 98, -1])

In [ ]:
arr = torch.arange(10)
arr.reshape()

RuntimeError: shape '[2]' is invalid for input of size 10

In [ ]:
# prompt: Convert a 1D tensor to a 2D tensor with 2 rows & 5 columns

import torch

# Create a 1D tensor
tensor = torch.arange(10)

# Convert the 1D tensor to a 2D tensor with 2 rows and 5 columns
tensor_2d = tensor.reshape(2, 5)

# Print the 2D tensor
print(tensor_2d)


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
