<a href="https://colab.research.google.com/github/yash5891/Deep-Learning/blob/main/SGD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
x=torch.rand(5,3)
x

tensor([[0.0513, 0.3595, 0.1517],
        [0.2917, 0.3038, 0.4376],
        [0.1232, 0.6168, 0.8096],
        [0.1633, 0.4585, 0.6073],
        [0.7731, 0.2955, 0.7734]])

In [ ]:
y = torch.rand(5)
y

tensor([0.8080, 0.8164, 0.5456, 0.5771, 0.8037])

In [ ]:
m = torch.randn(3,requires_grad=True)
m

tensor([ 2.1406, -1.2608,  0.1327], requires_grad=True)

In [ ]:
c = torch.randn(1,requires_grad=True)
c

tensor([-1.1902], requires_grad=True)

In [ ]:
x.T.shape

torch.Size([3, 5])

In [ ]:
model = lambda x : m @ x.T + c
y_pred = model(x)
y_pred

tensor([-1.5137, -0.8908, -1.5967, -1.3381,  0.1947], grad_fn=<AddBackward0>)

In [ ]:
loss = lambda y,y_pred: torch.sum(torch.abs(y-y_pred))
l=loss(y,y_pred)
l

tensor(8.6952, grad_fn=<SumBackward0>)

In [ ]:
l.backward()

In [ ]:
lr=0.01
m.data -= lr * m.grad
c.data -= lr * c.grad


tensor([-1.4027, -2.0341, -2.7796])

In [ ]:
a = torch.arange(4.,requires_grad=True)
a

tensor([0., 1., 2., 3.], requires_grad=True)

In [ ]:
mod = lambda x : (x**2)
b = mod(a)
b

tensor([0., 1., 4., 9.], grad_fn=<PowBackward0>)

In [ ]:
lo = lambda y:y.sum()
c = lo(b)
c

tensor(14., grad_fn=<SumBackward0>)

In [ ]:
c.backward()

In [ ]:
a.grad

tensor([0., 2., 4., 6.])